# Generated by Django 4.1.6 on 2023-02-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('total_score', models.CharField(max_length=3)),
                ('pass_score', models.CharField(max_length=3)),
                ('per_score', models.CharField(max_length=2)),
                ('regist_link', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=1000)),
                ('multiple_answer_yn', models.CharField(max_length=1)),
                ('question_answer', models.CharField(max_length=1)),
                ('question_answer_second', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump.test')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_order', models.CharField(max_length=1)),
                ('choice_text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump.question')),
            ],
        ),
    ]
